spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/mem;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
